import { toast } from "react-toastify";
import { useContext, useEffect, useCallback, useRef } from "react";
import { storeContext } from "../context/storeContext";
import { Link, useParams } from "react-router-dom";
import Spinner from "../components/Spinner";

// Import the CSS file for print and PDF-compatible styles
import "../printPdfStyles.css";

function ManageOrderItem() {
  const {
    orderData,
    orderFetcher,
    isLoading,
    setIsLoading,
    localTime,
    clockConverter,
    deliveryAddress,
    getDeliveryAddress,
    isManager,
    API_URL,
    APP_NAME,
  } = useContext(storeContext);

  const { id: orderId } = useParams();
  // Create a ref for the component's printable/downloadable area
  const componentRef = useRef();

  // --- Data Fetching and Initialization ---
  const fetchOrderDetails = useCallback(async () => {
    setIsLoading(true);
    try {
      await orderFetcher(orderId); // Fetch order data
    } catch (error) {
      console.error("Failed to fetch order details:", error);
      toast.error("Failed to load order details. Please try again.");
    } finally {
      setIsLoading(false);
    }
  }, [orderFetcher, orderId, setIsLoading]); // Depend on orderId and memoized functions

  useEffect(() => {
    fetchOrderDetails();
  }, []); // Re-fetch when fetchOrderDetails memoized function changes

  // Update dependent data (time and address) once orderData is available
  useEffect(() => {
    if (orderData && Object.keys(orderData).length > 0) {
      if (orderData.order && orderData.order.createdAt) {
        clockConverter(orderData.order.createdAt);
      }
      if (orderData.order && orderData.order.deliveryAddressId) {
        getDeliveryAddress(orderData.order.deliveryAddressId);
      }
    }
  }, []); // Depend on orderData and memoized functions

  // --- Print Functionality ---
  const handlePrint = () => {
    window.print();
  };

  // --- Render Loading State ---
  if (isLoading || !orderData || Object.keys(orderData).length === 0) {
    return <Spinner />;
  }

  // console.log(orderData.order);

  // Destructure order and products for easier access after loading
  const { order, products } = orderData;

  console.log(order);

  // Calculate VAT based on current order data
  // Assuming VAT is 7.5% as per original code comment
  const VAT = (0.075 * order.totalAmount).toFixed(2);

  return (
    <section className="bg-gray-50 py-8 sm:py-12">
      <div className="mx-auto max-w-screen-xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl bg-white p-6 rounded-lg shadow-lg">
          <header className="text-center mb-8">
            <h1 className="text-2xl sm:text-3xl font-extrabold text-gray-900 mb-2">
              📦 {order.user.isManager ? "Manager" : "Customer"} Order Details
            </h1>
            <p className="text-gray-600">Order ID: #{orderId}</p>
            {/* Display APP_NAME in the header */}
            {APP_NAME && (
              <p className="text-gray-500 text-sm mt-1">
                Generated by: {APP_NAME} via {API_URL}
              </p>
            )}
            {/* Print and Download Buttons - hidden when printing */}
            {order.transactionStatus === "success" && (
              <div className="flex justify-center gap-4 mt-4 no-print">
                <button
                  onClick={handlePrint}
                  className="inline-block rounded-full bg-blue-600 px-6 py-3 text-sm font-medium text-white transition hover:bg-blue-700 shadow-md"
                >
                  🖨️ Print Order
                </button>
              </div>
            )}
          </header>

          {/* This div contains the content that will be printed/downloaded */}
          <div ref={componentRef} className="printable-content">
            {/* Customer Details */}
            <div
              className="mb-8 p-6 rounded-lg border
                         pdf-compatible-blue-bg pdf-compatible-blue-border pdf-compatible-bg"
            >
              <h2
                className="text-xl font-semibold mb-4
                           pdf-compatible-blue-text"
              >
                👤 {order.user.isManager ? "Manager" : "Customer"} Information
              </h2>
              <p className="text-gray-700 mb-1">
                <strong>Name:</strong> {order.user.firstName}{" "}
                {order.user.lastName}
              </p>
              <p className="text-gray-700 mb-1">
                <strong>Email:</strong> {order.user.email}
              </p>
              <p className="text-gray-700">
                <strong>Mobile:</strong> {order.user.mobile}
              </p>
            </div>

            {/* Order Items */}
            <div
              className="mb-8 p-6 rounded-lg border
                         pdf-compatible-green-bg pdf-compatible-green-border pdf-compatible-bg"
            >
              <h2
                className="text-xl font-semibold mb-4
                           pdf-compatible-green-text"
              >
                🛒 Ordered Products
              </h2>
              <ul className="space-y-6">
                {products.map((product) => {
                  const orderItem = order.orderItems.find(
                    (item) => item.productId === product.id
                  );
                  // Ensure orderItem exists before trying to access its properties
                  if (!orderItem) return null;

                  const itemTotalPrice = (
                    product.price * orderItem.quantity
                  ).toFixed(2);

                  return (
                    <li
                      className="flex flex-col sm:flex-row items-center gap-4 border-b pb-4 last:border-b-0 last:pb-0"
                      key={product.id}
                    >
                      <Link
                        to={`/product/${product.id}`}
                        className="flex-shrink-0 no-print"
                      >
                        <img
                          src={product.imageUrl}
                          alt={product.title}
                          className="h-20 w-20 rounded-md object-cover shadow-sm no-print"
                        />
                      </Link>

                      <div className="flex-1 text-center sm:text-left">
                        <h3 className="text-base font-medium text-gray-900">
                          {product.title.length > 60
                            ? product.title.substring(0, 60) + "..."
                            : product.title}
                        </h3>
                        <p className="text-sm text-gray-500">
                          Price: ₦{Number(product.price).toLocaleString()} NGN{" "}
                        </p>
                      </div>

                      <div className="flex items-center gap-3 text-sm font-semibold">
                        <span className="px-3 py-1 bg-gray-100 rounded-md">
                          Qty: {orderItem.quantity}
                        </span>
                        <span className="px-3 py-1 bg-indigo-100 text-indigo-800 rounded-md">
                          Total: ₦{Number(itemTotalPrice).toLocaleString()} NGN{" "}
                        </span>
                      </div>
                    </li>
                  );
                })}
              </ul>
            </div>

            {/* Delivery and Transaction Details */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
              {/* Delivery Details */}
              <div
                className="p-6 rounded-lg border
                           pdf-compatible-yellow-bg pdf-compatible-yellow-border pdf-compatible-bg"
              >
                <h2
                  className="text-xl font-semibold mb-4
                             pdf-compatible-yellow-text"
                >
                  🚚 Delivery Details
                </h2>
                <dl className="space-y-2 text-sm text-gray-700">
                  <div className="flex justify-between items-start">
                    <dt className="font-medium">Address:</dt>
                    <dd className="text-right flex-1 ml-4">
                      {order.deliveryAddress.address}
                    </dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="font-medium">Mobile Number:</dt>
                    <dd>{order.deliveryAddress.mobile}</dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="font-medium">Full Name:</dt>
                    <dd>
                      {order.deliveryAddress.firstName}{" "}
                      {order.deliveryAddress.lastName}
                    </dd>
                  </div>
                </dl>
              </div>

              {/* Transaction Details */}
              <div
                className="p-6 rounded-lg border
                           pdf-compatible-purple-bg pdf-compatible-purple-border pdf-compatible-bg"
              >
                <h2
                  className="text-xl font-semibold mb-4
                             pdf-compatible-purple-text"
                >
                  💸 Transaction Summary
                </h2>
                <dl className="space-y-2 text-sm text-gray-700">
                  <div className="flex justify-between">
                    <dt className="font-medium">Date of Transaction:</dt>
                    <dd>{localTime || "N/A"}</dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="font-medium">Transaction Status:</dt>
                    <dd>{order.transactionStatus}</dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="font-medium">Payment Method:</dt>
                    <dd>{order.paymentMethod}</dd>
                  </div>
                  <div className="flex justify-between font-bold text-base mt-4 pt-2 border-t border-gray-200">
                    <dt>VAT (7.5%):</dt>
                    <dd>₦{Number(VAT).toLocaleString()} NGN </dd>
                  </div>
                  <div className="flex justify-between font-bold text-base mt-4 pt-2 border-t border-gray-200">
                    <dt>Discount:</dt>
                    <dd>
                      ₦{Number(order.discountAmount).toLocaleString()} NGN -{" "}
                      {order.discountPaymentStatus}{" "}
                    </dd>
                  </div>
                  <div className="flex justify-between !text-lg font-extrabold text-gray-900">
                    <dt>Grand Total:</dt>
                    <dd>
                      ₦
                      {Number(
                        Number(order.totalAmount) - Number(order.discountAmount)
                      ).toLocaleString()}{" "}
                      NGN{" "}
                    </dd>
                  </div>
                </dl>
              </div>
            </div>
          </div>

          {/* Back button - hidden when printing */}
          <div className="mt-8 text-center no-print">
            <Link
              to={`/${isManager ? "manager" : "admin"}/manage-orders`}
              className="inline-block rounded-full bg-gray-800 px-6 py-3 text-sm font-medium text-gray-100 transition hover:bg-gray-700 shadow-md"
            >
              ⬅️ Back to All Orders
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

export default ManageOrderItem;
